import type { Question } from './types';
// q1–q4 adapt the situations already used in src/content/scenes.ts.
// Additional questions paraphrase the same teaching points, not new quotations.
export const QUESTIONS: Question[] = [
  // --- CHỦ ĐỀ: ĐỘC LẬP (rights) ---
  {
    id: 'dl-47',
    topic: 'rights',
    text: 'Theo Hồ Chí Minh, vấn đề cốt lõi của cách mạng giải phóng dân tộc thuộc địa là gì?',
    options: [
      'Vấn đề tự do dân chủ',
      'Vấn đề độc lập dân tộc',
      'Vấn đề ruộng đất',
      'Vấn đề đấu tranh giai cấp',
    ],
    answer: 1,
    explanation: 'Hồ Chí Minh xác định độc lập dân tộc là vấn đề cốt lõi, trên hết và trước hết của cách mạng thuộc địa.',
    source: 'Tư tưởng Hồ Chí Minh · QN=47',
  },
  {
    id: 'dl-54',
    topic: 'rights',
    text: 'Theo tư tưởng Hồ Chí Minh, luận điểm nào sau đây là đúng?',
    options: [
      'Độc lập dân tộc gắn liền với chủ nghĩa xã hội.',
      'Giải phóng dân tộc gắn liền với chủ nghĩa xã hội.',
      'Giải phóng dân tộc gắn với chủ nghĩa dân tộc.',
      'Độc lập dân tộc gắn liền với chủ nghĩa tư bản.',
    ],
    answer: 0,
    explanation: 'Độc lập dân tộc gắn liền với chủ nghĩa xã hội là tư tưởng cốt lõi, sợi chỉ đỏ xuyên suốt đường lối cách mạng của Hồ Chí Minh.',
    source: 'Tư tưởng Hồ Chí Minh · QN=54',
  },
  {
    id: 'dl-56',
    topic: 'rights',
    text: 'Về quyền độc lập dân tộc, Hồ Chí Minh cho rằng:',
    options: [
      'Giữ vững độc lập của dân tộc mình đồng thời tôn trọng độc lập của các dân tộc khác',
      'Giữ vững độc lập của dân tộc mình đồng thời kính trọng độc lập của các dân tộc khác',
      'Giữ vững độc lập của dân tộc mình đồng thời tôn trọng độc lập của các quốc gia',
      'Giữ vững độc lập của dân tộc mình và không quan tâm đến các dân tộc khác',
    ],
    answer: 0,
    explanation: 'Hồ Chí Minh nêu cao tinh thần độc lập tự chủ nhưng luôn tôn trọng quyền độc lập, tự quyết thiêng liêng của mọi dân tộc khác.',
    source: 'Tư tưởng Hồ Chí Minh · QN=56',
  },
  {
    id: 'dl-60',
    topic: 'rights',
    text: 'Hồ Chí Minh vạch ra mục tiêu của cách mạng giải phóng dân tộc thuộc địa là gì?',
    options: [
      'Lật đổ ách thống trị của chủ nghĩa đế quốc, giành độc lập dân tộc, giành chính quyền về tay nhân dân',
      'Lật đổ ách thống trị của chủ nghĩa đế quốc, giành độc lập dân tộc, giành chính quyền về tay người lao động',
      'Lật đổ ách thống trị của chủ nghĩa đế quốc, giành độc lập dân tộc, giành chính quyền về tay lực lượng cách mạng',
      'Lật đổ ách thống trị của chủ nghĩa đế quốc, chuyển giao chính quyền cho giai cấp tư sản',
    ],
    answer: 0,
    explanation: 'Mục tiêu là đánh đổ ách thống trị của chủ nghĩa đế quốc, giành độc lập dân tộc và đưa chính quyền về tay nhân dân.',
    source: 'Tư tưởng Hồ Chí Minh · QN=60',
  },
  {
    id: 'dl-33',
    topic: 'rights',
    text: 'Trong Thư gửi UBND các cấp (17-10-1945), Hồ Chí Minh viết: "Nếu nước độc lập mà dân không hưởng hạnh phúc tự do, thì ................... cũng chẳng có nghĩa lý gì".',
    options: [
      'tự do',
      'độc lập',
      'hạnh phúc',
      'tự chủ',
    ],
    answer: 1,
    explanation: 'Trích nguyên văn Thư gửi UBND các kỳ, tỉnh, huyện và làng (17/10/1945): "...thì độc lập cũng chẳng có nghĩa lý gì".',
    source: 'Báo Cứu quốc, số 69 (17/10/1945)',
  },

  // --- CHỦ ĐỀ: TỰ DO (rights) ---
  {
    id: 'td-1',
    topic: 'rights',
    text: 'Theo tư tưởng Hồ Chí Minh, “Tự do nhân dân” được xác định chủ yếu là mục tiêu thuộc bình diện nào?',
    options: [
      'Chính trị',
      'Xã hội',
      'Kinh tế',
      'Văn hóa',
    ],
    answer: 1,
    explanation: 'Trong cấu trúc các giá trị độc lập - tự do - hạnh phúc, tự do nhân dân được xác định gắn với bình diện xã hội.',
    source: 'Tư tưởng Hồ Chí Minh · Tự do',
  },
  {
    id: 'td-2',
    topic: 'rights',
    text: 'Nội dung cốt lõi của tự do nhân dân theo tư tưởng Hồ Chí Minh là gì?',
    options: [
      'Người dân được tự do kinh doanh không giới hạn',
      'Mỗi cá nhân được sống hoàn toàn độc lập với xã hội',
      'Nhân dân được làm chủ, được bảo đảm các quyền tự do và dân chủ',
      'Nhà nước không can thiệp vào đời sống của người dân',
    ],
    answer: 2,
    explanation: 'Cốt lõi của tự do nhân dân là nhân dân thực sự được làm chủ đất nước, được bảo đảm mọi quyền tự do và dân chủ.',
    source: 'Tư tưởng Hồ Chí Minh · Tự do',
  },
  {
    id: 'td-3',
    topic: 'rights',
    text: 'Ngay từ năm 1919, trong Yêu sách của nhân dân An Nam, Nguyễn Ái Quốc đã yêu cầu những nội dung nào liên quan trực tiếp đến tự do?',
    options: [
      'Quyền sở hữu đất đai và quyền kinh doanh',
      'Quyền bình đẳng về pháp lý và các quyền tự do, dân chủ',
      'Quyền thành lập quân đội riêng',
      'Quyền miễn thuế cho người dân',
    ],
    answer: 1,
    explanation: 'Bản Yêu sách 8 điểm (1919) đòi quyền bình đẳng về pháp lý và các quyền tự do, dân chủ cơ bản cho người dân An Nam.',
    source: 'Yêu sách của nhân dân An Nam (1919)',
  },
  {
    id: 'td-4',
    topic: 'rights',
    text: 'Câu nói “Bao nhiêu quyền hạn đều của dân… quyền hành và lực lượng đều ở nơi dân” thể hiện rõ nhất quan niệm nào?',
    options: [
      'Độc lập dân tộc là mục tiêu duy nhất của cách mạng',
      'Nhà nước quyết định toàn bộ quyền lợi của nhân dân',
      'Nhân dân là chủ thể của quyền lực trong chế độ dân chủ',
      'Tự do chỉ được thực hiện sau khi kinh tế phát triển',
    ],
    answer: 2,
    explanation: 'Khẳng định nhân dân là chủ thể của mọi quyền lực; bản chất của dân chủ là quyền lực thuộc về nhân dân.',
    source: 'Tác phẩm "Dân vận" (1949)',
  },
  {
    id: 'td-5',
    topic: 'rights',
    text: 'Mối quan hệ giữa tự do và hạnh phúc trong tư tưởng Hồ Chí Minh được hiểu đúng nhất như thế nào?',
    options: [
      'Tự do và hạnh phúc hoàn toàn độc lập với nhau',
      'Chỉ cần đời sống vật chất đầy đủ thì không cần tự do',
      'Có tự do thì tự động có hạnh phúc',
      'Tự do tạo điều kiện để con người mưu cầu hạnh phúc, còn hạnh phúc là sự hiện thực hóa thực tế của quyền tự do',
    ],
    answer: 3,
    explanation: 'Tự do tạo điều kiện và môi trường để con người mưu cầu hạnh phúc, còn hạnh phúc là sự hiện thực hóa cụ thể của quyền tự do trong đời sống.',
    source: 'Tư tưởng Hồ Chí Minh · Tự do - Hạnh phúc',
  },

  // --- CHỦ ĐỀ: HẠNH PHÚC (people) ---
  {
    id: 'hp-1',
    topic: 'people',
    text: 'Theo tư tưởng Hồ Chí Minh, “Hạnh phúc con người” được xác định là mục tiêu thuộc bình diện nào?',
    options: [
      'Chính trị',
      'Xã hội',
      'Con người',
      'Kinh tế',
    ],
    answer: 2,
    explanation: 'Hạnh phúc con người được xác định hướng trực tiếp vào bình diện con người - sự phát triển và đời sống của mỗi cá nhân.',
    source: 'Tư tưởng Hồ Chí Minh · Hạnh phúc',
  },
  {
    id: 'hp-2',
    topic: 'people',
    text: 'Theo Hồ Chí Minh, hạnh phúc của nhân dân phải được thể hiện như thế nào?',
    options: [
      'Chỉ cần có quyền tự do chính trị',
      'Chỉ cần đời sống vật chất đầy đủ',
      'Được bảo đảm cả đời sống vật chất và đời sống tinh thần',
      'Chỉ cần đất nước có chủ quyền',
    ],
    answer: 2,
    explanation: 'Hạnh phúc của nhân dân phải được biểu hiện toàn diện, kết hợp hài hòa cả đời sống vật chất lẫn đời sống tinh thần.',
    source: 'Tư tưởng Hồ Chí Minh · Hạnh phúc',
  },
  {
    id: 'hp-3',
    topic: 'people',
    text: 'Câu nói “Nước độc lập mà dân không hưởng hạnh phúc tự do, thì độc lập cũng chẳng có nghĩa lý gì” nhấn mạnh điều gì?',
    options: [
      'Hạnh phúc quan trọng hơn độc lập dân tộc',
      'Độc lập và hạnh phúc không liên quan với nhau',
      'Giá trị của độc lập phải được thể hiện trong đời sống tự do, hạnh phúc của nhân dân',
      'Chỉ khi kinh tế phát triển mới cần quan tâm đến độc lập',
    ],
    answer: 2,
    explanation: 'Độc lập dân tộc chỉ có ý nghĩa thực sự khi mang lại cuộc sống ấm no, tự do và hạnh phúc thực tế cho người dân.',
    source: 'Thư gửi UBND các kỳ, tỉnh, huyện và làng (17/10/1945)',
  },
  {
    id: 'hp-4',
    topic: 'people',
    text: 'Theo Hồ Chí Minh, những nhu cầu thiết yếu nào thể hiện hạnh phúc thực tế của nhân dân?',
    options: [
      'Có quyền kinh doanh, đi du lịch và sở hữu tài sản',
      'Có ăn, có mặc, có chỗ ở và được học hành',
      'Có địa vị xã hội và thu nhập cao',
      'Có quyền tham gia mọi tổ chức chính trị',
    ],
    answer: 1,
    explanation: 'Hồ Chí Minh đúc kết nhu cầu hạnh phúc thiết thực nhất của nhân dân là: ai cũng có cơm ăn, áo mặc, có chỗ ở và được học hành.',
    source: 'Hồ Chí Minh Toàn tập',
  },
  {
    id: 'hp-5',
    topic: 'people',
    text: 'Trong tư tưởng Hồ Chí Minh, hạnh phúc con người giữ vai trò nào trong sự nghiệp cách mạng?',
    options: [
      'Là điều kiện đầu tiên để giành độc lập',
      'Là phương tiện để phát triển kinh tế',
      'Là mục tiêu tạm thời sau khi giành chính quyền',
      'Là đích đến tối hậu và thước đo thực tế của thành quả cách mạng',
    ],
    answer: 3,
    explanation: 'Hạnh phúc con người là đích đến tối hậu, là mục đích cao nhất và cũng là thước đo thực tế nhất cho thành quả của toàn bộ sự nghiệp cách mạng.',
    source: 'Tư tưởng Hồ Chí Minh · Hạnh phúc',
  },
];
export const questionById = (id:string) => QUESTIONS.find(q=>q.id===id)!;
